AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'db.bak/**/*'
    - 'app/helpers/bootstrap_flash_helper.rb'

Metrics/LineLength:
  Exclude:
    - Rakefile
    - config/puma.rb
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
