# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 323aa5c40288a22239d2e5db7d080bd1483f6a101af75a79738ffbe441b322f6243a5c32ff41f3c1faf91140c7fd2b8c1972bcaf64ada1297c716e2e4bd4cc4b

test:
  secret_key_base: da22cd7e3e234e4daa20195a119b4dac54e45c7de5515b9654815d943baf08bde55603cd732f0cb61ac4656e01356927710f38a672eb99571aaec8030fc92425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
